### ISSUE TITLE
[bug] Cannot unlock an item on the canvas

### ISSUE THREAD

**Issue by akivajgordon** [tldraw/tldraw#1039]
As shown in the attached video, I can lock an item, but I cannot unlock it because I cannot seem to select it using several approaches:

* trying to select it with the pointer
* trying to select it by dragging a bounding select box around it

I was, however, able to right-click it to bring up a context menu that allowed me the option to unlock it, but on mobile, I only get the options of `Paste`, `Undo`, and `Redo`.

If this is all intended behavior, it doesn't feel intuitive. If it's a bug, then it seems to be the inability to select the locked item.

Found on Safari 16.1 on macOS Ventura and Safari on iOS 16. I admit that I haven't tried other browsers.

https://user-images.githubusercontent.com/6025036/201093998-25c000c2-e154-4a48-bd48-17ccb5e85353.mov

**Comment by steveruizok** [comment]
That's currently the correct behavior. We've actually taken this feature out of the next version: without an objects list or some other way of selecting a shape, the only way to "unlock" a shape is through the right click menu. This also means that if you lock multiple shapes, you need to right click on each one individually in order to unlock them. :/

**Comment by akivajgordon** [comment]
@steveruizok Is there a plan for addressing this on the mobile version? As I mentioned previously, I only get "Paste", "Undo", and "Redo". How do I unlock the object?

**Comment by alex-kim-dev** [comment]
@akivajgordon I was able to select a locked shape with a double tap on mobile, then 3-dotted menu and unlock.
