### ISSUE TITLE
[windows chrome] Pasted PNGs are scaled incorrectly

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#1457]
1. draw a draw shape
2. copy-as png
3. paste
4. it's twice as big as the copied shape

Failure of this ticket https://github.com/tldraw/tldraw/pull/1200

**Comment by steveruizok** [comment]
Update because someone reported this as a bug: chrome strips this data from pasted images. There's nothing straightforward that we can do about it, though maybe we can sneak "hey the scale is actually 2" data into the name, width, or something else, so that we can at least recognize our own png scales on paste.
