### ISSUE TITLE
Sync issues with shared projects

### ISSUE THREAD

**Issue by TodePond** [tldraw/tldraw#1576]
Sometimes, when you joined, you joined the same room (Room A) as other people. But sometimes, you joined a different room (Room B).

Room A was continuing fine as a shared project while someone was in Room B.
When someone from Room A refreshed, they appeared in Room B.

We saw this happen in an old room (staging.tldraw.com/r/d), as well as a brand new room.

**Comment by TodePond** [comment]
Maybe we can show @ds300 when he's back :)

**Comment by ds300** [comment]
Ooof sounds like i broke the persistenceKey handling server side somehow. Looking into it.

**Comment by ds300** [comment]
I'm 95% sure that these issues were fixed by https://github.com/tldraw/brivate/pull/2062 and that what appeared to be separate rooms were actually the same rooms with old vs new data?

Either way I haven't been able to reproduce the issues other than the data-not-saving thing, and I spent a good long while today doing manual testing, and reading through the changes I made last week.

**Comment by steveruizok** [comment]
Closing, I think this one was fixed.
