### ISSUE TITLE
Cannot export large images in Firefox

### ISSUE THREAD

**Issue by senntore** [tldraw/tldraw#1669]
### What happened?

I cannot export a file as png(jpg is not available in the newer version right now) when there are more than 5 images present in the new version of tldraw even when I try to make the image board smaller.
I expected it to export the file as intended & how it used to work in the older version.

### How can we reproduce the bug?

In a new tldraw file:
1. Insert 6 or more images
2. Select all images & then export as png.
3. See the issue, screenshot: 
![image](https://github.com/tldraw/tldraw/assets/58325574/cad7f341-1775-48c8-983b-c539d49db39c)
4. Remove one or more images, to have 5 or less images in the file.
5. Try exporting again as png. Take note if the export was success or not.

By the way you can use this tldraw file as an example, https://www.tldraw.com/r/WPH2voP2nS-QTXabIfEdl?viewport=1708%2C-1604%2C6284%2C3006&page=page%3AHPHO3SMwyHXWB3Opxf2Eb

Note: I had another question, will there be jpg option for export in the future version anytime soon? Jpg is usually smaller in size than png & works better with digital artworks & similar images. 
I mostly use tldraw as a way to organize to images for mood boards, so I hope you can fix this. In the mean time I have to use old.tldraw.com or the Logseq's whiteboard(It's great to have tldraw there)

### What browsers are you seeing the problem on?

Firefox

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by senntore** [comment]
I tried exporting again in Brave browser & it seems that the export is working as intended in chromium but not in Firefox.

**Comment by steveruizok** [comment]
Firefox has been weird with images. My guess is that the issue is actually the size of the images rather than the number of images. I was able to get more than five exporting without an issue, however those are smaller images.

When we export images from tldraw, we first create an SVG element that includes all the content that you're exporting. In this SVG, images are serialized into base64 strings. Next we turn the SVG itself into a string (the "dataUrl"), then create an HTML Canvas element and paint an image onto the canvas using the dataUrl as the image content. Then we export the canvas as a PNG.

The issue seems to be the maximum length of that dataUrl. According to MDN, Firefox has a much smaller limit to the size of the dataUrl than Safari or Chrome:

> Browsers are not required to support any particular maximum length of data. For example, the Opera 11 browser limited URLs to 65535 characters long which limits data URLs to 65529 characters (65529 characters being the length of the encoded data, not the source, if you use the plain data:, without specifying a MIME type). **Firefox version 97 and newer supports data URLs of up to 32MB (before 97 the limit was close to 256MB).** Chromium objects to URLs over 512MB, and Webkit (Safari) to URLs over 2048MB.

The size of a image as text (the base64) is larger than the size of a regular image, so it doesn't take much to hit that 32 mb. My guess is that's what happening here. Unfortunately there's not much we can do about it from our side, apart from changing our approach to image exports. We could re-scale image manually before serializing, which would make images smaller where they've been cropped or resized, but I don't think that would help here. We'll keep it flagged though in case we come up with a better way to do image exports.

**Comment by senntore** [comment]
Well I've tried making the images much smaller but still cannot export 6 or more images, see the tldraw file I shared above.
And I can export very large images if there are only 5 or less images(with export size around 100 mb).
This issue doesn't exist in older version of tldraw in firefox, so maybe it's worth looking how the export was done in that version compared to current version.
