### ISSUE TITLE
Add advanced markdown rendering

### ISSUE THREAD

**Issue by bebeal** [tldraw/tldraw#1736]
### What's the feature?

I'm interested in improvements to `TextShape` and `TextLabel` to extend their rendering capabilities. The proposed enhancements include adding support for:
* Markdown
* Code Blocks with Syntax Highlighting
* Math Typesetting

This would greatly benefit the scientific and academia/educational community and in my eyes would make the app near perfect. There's also some great opportunity for new interactions with these additions such as a [Detexify -like](https://detexify.kirelabs.org/classify.html) feature to translate handwriting -> math symbol. [Draw.io](https://www.drawio.com/doc/faq/math-typesetting) has support for this via AsciiMath and MathJax and it integrates very nicely into diagrams.

I implemented a very quick proof of concept of this that leverages the remark ecosystem, mainly
* [`remark`](https://github.com/remarkjs/remark)
* [`remark-rehype`](https://github.com/remarkjs/remark-rehype)
* [`remark-gfm`](https://github.com/remarkjs/remark-gfm) // for [github flavored markdown](https://github.github.com/gfm/) support
* [`rehype-katex`](https://github.com/remarkjs/remark-math/tree/main/packages/rehype-katex) // for [KaTeX](https://katex.org/) mathematical typesetting
* [`rehype-highlight`](https://github.com/rehypejs/rehype-highlight) // for syntax highlighting via [highlight.js](https://github.com/isagalaev/highlight.js)
* [`rehype-sanitize`](https://github.com/rehypejs/rehype-sanitize) // for user input sanitation enforcing safe HTML

https://github.com/tldraw/tldraw/assets/42706447/00ef49eb-48f1-4114-8ad0-3f72aca98848

This easily takes care of most of the actual feature implementation itself but there would obviously be a bit of work needed to further integrate this. Particularly the important areas I can think of would be:

* Text measurement and bounding box adjustments
  * when editing and w/ respect to the actual output
* Keeping exports visually correct
* Making this toggleable/optional
* interactions with the current text options such as alignment, font-size, font, etc

---

Thoughts on supporting this? How much of this should depend on libraries/new dependencies vs internal implementation?

### Contact Details

bnoahbeal@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Impressive spike! And thanks for the thoughtful issue.

Markdown support has come up before and unfortunately the same arguments still apply for why we don't support it. If we were going to implement this on tldraw.com, it would have to be wysiwyg (using Lexical, Prosemirror / Tiptap, etc). In fact we did have this in an earlier version of tldraw but dropped it due to the complexity it added, especially on mobile where the interactions were sometimes very inconsistent. And image export was indeed difficult as you suggested, though I think we would have an easier time now with our current strategy for text export.

I try to keep a pretty high bar for the features that make it into tldraw, so the question is really about capacity to research and implement a solution that ticks all of our boxes without sacrificing quality.

**Comment by bebeal** [comment]
Thanks for the quick reply. Totally get your concerns about maintaining the the high quality of tldraw. I'm game to give this a decent shot though. If it doesn't meet the bar for the main branch, no worries. I can always chuck it onto a forked feature branch for others to explore.

Was that earlier markdown-supporting version of tldraw ever public? I'm assuming it was on the old v1 version but would still be cool to take a look at it. I'll play around with using Lexical and/or Tiptap and share my results. Will definitely lean and extend upon the export-snapshots test as I go. 

Regarding the mobile interaction could you elaborate on what was inconsistent about it?

**Comment by steveruizok** [comment]
No, it wasn't public, but here's a link the code as a gist: https://gist.github.com/steveruizok/8e534fc443df2066ed0df6fdb4d1d8a0. You could also of course look at our current text shape. Note especially the places where we need to measure text: we can't rely on the result of React's render to tell us the dimensions of the text, so we need to measure it externally (e.g. with a "measurement div") in order to calculate the shape's size before we render. It's a bit of a juggling act, good luck!

**Comment by mrmianbao** [comment]
+1 to adding a code block shape, for any technical diagramming it's a must have.

**Comment by nileshtrivedi** [comment]
@bebeal Did you publish your tldraw repo with `remark` integrated somewhere?  It would be great to use as a base library for all kinds of plugins/extensions. For eg: I would like to use it for a Zotero plugin.
