### ISSUE TITLE
Improve UX

### ISSUE THREAD

**Issue by 1tang2bang92** [tldraw/tldraw#1742]
### What's the feature?

hello. I'm a new user to tldraw.
I translated this article into deepl.

tldraw is a very good program and I want to use it often in the future, but there are some things I would like to see added.

1. I would like to add the ability to change the size of the eraser.
2. the screen zoom function should be improved. Currently, it zooms in or out step by step according to the aspect ratio of the browser, but I would like to have a smooth zoom function on tablets like Photoshop.
3. I'd like to see a feature to soften lines.

Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
Thanks for the feedback! There's several issues here that I'll refer you to other bugs to help you track the progress (Subscribe on the issues to track)
- our eraser doesn't work on size but on intersection - it only matters if you touch an object
- we've since adde a camera API that helps with animation https://examples.tldraw.com/camera-options
- for customizing lines we're tracking that here: https://github.com/tldraw/tldraw/issues/3470
