### ISSUE TITLE
[Bug]: laggy UI on fast scrolls

### ISSUE THREAD

**Issue by lakesare** [tldraw/tldraw#1762]
### What happened?

We updated tldraw from `2.0.0-alpha.14` to `^2.0.0-canary.4bd8a257ac02` (current main basically), and we started seeing some artifacts that look like "lazy loading".

### Before:

<img width="200px" src="https://github.com/tldraw/tldraw/assets/7578559/52fa54a6-307c-460d-9dbf-43ac3aea3d7d)"/>

### After:

<img width="200px" src="https://github.com/tldraw/tldraw/assets/7578559/491005e2-0ee1-4d64-9525-7f6f1390ebd8)"/>

### How can we reproduce the bug?

1. Create 100 shapes
2. Scroll around back and forth reasonably quickly

### What browsers are you seeing the problem on?

Firefox, Chrome

**Comment by adi-bhatl-1998** [comment]
i see this issue in 2.0.0-alpha.14 too .

**Comment by lakesare** [comment]
PSA: subclassing all components that are getting culled and setting `override canUnmount = () => false` works, to hell with performance 😄 

<img width="558" alt="image" src="https://github.com/tldraw/tldraw/assets/7578559/b91e0bbf-4859-4d8d-9719-05d967e59a73">

**Comment by adi-bhatl-1998** [comment]
how'd you figure it out ?

**Comment by lakesare** [comment]
Oh they got rid of this line in 9-hours-ago commit (https://github.com/tldraw/tldraw/commit/e4829f67023df6097d06eef484305ca0c0faee44), it used to be like that:

![image](https://github.com/tldraw/tldraw/assets/7578559/becfe50f-5600-4785-b983-408f4c3971af)
<img width="729" alt="image" src="https://github.com/tldraw/tldraw/assets/7578559/dc0a7916-9e0f-4066-8bf3-8ee58484d495">

That commit might be fixing this issue altogether though, needs to be checked.

**Comment by adi-bhatl-1998** [comment]
can you share the file name in the repo ?

**Comment by lakesare** [comment]
https://github.com/tldraw/tldraw/blob/e4829f67023df6097d06eef484305ca0c0faee44/packages/editor/src/lib/components/Shape.tsx#L121

**Comment by steveruizok** [comment]
That effect is actually by design! 

We disabled it accidentally a few versions ago and have now restored it.

There are a few reasons why we do things that way.

If we leave everything in the DOM then there can be memory / performance issues when having lots of shapes in the project, even when those shapes are off screen. It's generally better to "cull" off screen shapes and instead only include the on-screen shapes in the DOM.

Unfortunately, mounting / unmounting shapes is also expensive. If we mount / unmount shapes as soon they appear on the screen or leave the screen, then we end up doing that expensive work during other expensive work—scrolling or zooming—which causes those interactions to be slow.

Instead, we wait until you've stopped zooming or panning before restoring the shapes. In the meantime, we display grey boxes which are placeholders for the "culled" shapes.

We could still make some improvements:
- tweaking the delay before we mount shapes
- requiring a certain number of shapes before we turn this effect on
- allowing a "developer" user to turn it off completely

**Comment by lakesare** [comment]
> requiring a certain number of shapes before we turn this effect on
> allowing a "developer" user to turn it off completely

I things these two would be great, especially the latter.

Our usecase e.g. is always max 40 shapes and scrolling around is frequent and needs to be flawless/non-distracting.

**Comment by steveruizok** [comment]
Ok, I'm going to set it so that setting the `Editor.renderingBoundsMargin` to `Infinity` will keep all shapes on screen at all times (unless they're clipped by a frame).

**Comment by lakesare** [comment]
Thanks, does work in my code!
