### ISSUE TITLE
[Feature]: Paste larger images in full resolution

### ISSUE THREAD

**Issue by thomasaull** [tldraw/tldraw#1773]
### What's the feature?

Copy and Pasting a image of, say 200×200 px shows the image in original resolution on the tldraw canvas. A larger image, for example 2000×2000 px though will automatically get resized. This, in my opinion, is not desired behaviour. I'd rather have the image in full resolution for annotations etc. An option to always paste in full resolution would be an alternative too.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
IIRC if the image you pasted is bigger than the viewport it will resized! I think resizing is good for a better perf(we can load the image quickly), but as you said
> An option to always paste in full resolution would be an alternative too.

that's maybe a good thing but let's the what the tldraw team think cc @steveruizok

**Comment by steveruizok** [comment]
Hey @thomasaull, we re-scale all images to fit into a 1000x1000 box. For local images, this is done for performance reasons (serializing a 10mb means having a 13mb string in your html); and for shared projects, we do it for sanity / storage reasons. We might be able to loosen that rule for local projects, especially if we end up with something like an electron app where files could still be referenced by a local URL rather than a base64 string. For shared rooms, it could end up being a feature for logged in users, as "large anonymous image hosting" is generally risky business but "large non-anonymous image hosting" might be doable.

**Comment by thomasaull** [comment]
@steveruizok You might not even need to have an electron app for this, I think the File System API provides access and read/write for entire directories now. So you could prompt the user to set a folder on it's drive for image storage. Though, it might be less convenient and/or more confusing compared to an electron app which does it all by itself.

In the meantime I'm gonna make sure to not grab anything larger than 1000×1000 px :)

**Comment by steveruizok** [comment]
Cheers, I'll look into this. In the meantime, what kind of UX would have been good here? A little dialog saying "hey we had to resize this"?

**Comment by judicaelandria** [comment]
I think the toast work here saying your image is bigger than the viewport so we had to resize it?

**Comment by steveruizok** [comment]
It's not that the image is bigger than the viewport, it's just anything over 1000px on either side will cause us to rescale the image.

**Comment by steveruizok** [comment]
Working on some APIs to address this: https://github.com/tldraw/tldraw/pull/1824

**Comment by steveruizok** [comment]
I landed the props in https://github.com/tldraw/tldraw/pull/1824 which will allow developers more control over when (and whether) to rescale images which are too large or reject files which are too large. I think the limits that we have in the local editor will need to stay for performance reasons (decoding a base64 source is CPU blocking), however I'll look at adjusting our rules for the multiplayer editor, where files are hosted and so have less impact on performance.

**Comment by WillTaylor22** [comment]
Great job on #1824 Steve, and the rest of TLDraw

The serialisation of big images might be a deal breaker for us, as our use-case is around allowing branding agencies / designers to get feedback on their work, so high res images are the norm. Currently serialising even a 2.6mb JPG is causing some meaningful frame-rate issues on my Macbook Pro https://www.loom.com/share/813544f7b1db4752a8e22bac83824be6
This is TLDRaw Canary 15 (2.0.0-canary.b6ebe1e2749e)

Appreciate this use case is probably stretching what TLDraw is meant for, but just thought I'd share the data!

**Comment by gaurav21r** [comment]
+1 Our specific Use Case is related to building a Social Media Planner / Calendar where, as you can Imagine, the original Res Image is critical!

@steveruizok The particular performance optimisations you are talking about (and the flickering suggested by @WillTaylor22 , is it because of the length limitations of base64 encoding or the fact that a 4000X4000 px image in the canvas itself will cause a slow down?

We are architecting our own Image Upload solution which will use S3 buckets and saving the URL to the Editor.Store. When offline, the URL will point to binary Data being stored locally in IndexedDB. IndexedDB is capable handling large binary data.

Asking this to predict if we will also hit perfomance issues in the canvas with large image rendering or is it a base64 issue?

I am assuming the TlDraw canvas does some sort of virtual rendering like react-window (ie only drawing the DOM which is visible).

**Comment by mimecuvalo** [comment]
We've done a lot of work here recently to enable this functionality. Starting in version 2.3.0 we've now setup hooks so that you can get higher/lower resolution size for images depending on the context (things like your viewport, zoom level, current network speed, among other considerations).

You can take a look at how we're doing this in multiplayer rooms on tldraw.com (upload a high-res image and zoom in-and-out on a multiplayer room, not single player, and you'll see it transforming the image on demand). We use Cloudflare's image transform to help resize things: https://developers.cloudflare.com/images/transform-images/

Here are the relevant files if you want to setup something custom yourselves in your hand-rolled tldraw instances:
- https://github.com/tldraw/tldraw/blob/main/apps/dotcom/src/utils/multiplayerAssetStore.ts
- https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/shared/useAsset.ts
- and then finally it all comes together in: https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/shapes/image/ImageShapeUtil.tsx

You can also look at other full-fleged examples:
- https://github.com/tldraw/tldraw/blob/main/apps/simple-server-example/src/client/App.tsx#L41-L65
- or, our Cloudflare workers template: https://github.com/tldraw/tldraw/tree/main/templates/cloudflare-workers (that does the same as above in the `client/App.tsx` file)

This issue is considered resolved! Please do reach out on Discord if you need any tips/help on implementing this on your own instances: https://discord.com/invite/SBBEVCA4PG

**Comment by thomasaull** [comment]
This is awesome, now I can use tldraw for all my annotations needs. Thank you so much everyone involved for such an amazing tool!
