### ISSUE TITLE
Pinch zoom extremely slow on Safari

### ISSUE THREAD

**Issue by leolorenzoluis** [tldraw/tldraw#1805]
### What happened?

Pinching in trackpad in Chrome fires scroll.  Safari it's pinch hence I don't see the slowness in Chrome
CMD + Scroll in trackpad in Safari is fast because it fires scroll hence it's almost similar speed.

### How can we reproduce the bug?

Go to tldraw.com and add 100 shapes. Pinch using trackpad to zoom in and out

### What browsers are you seeing the problem on?

Safari

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Can reproduce, thanks for the bug @leolorenzoluis.

I was looking into this but couldn't find the fix before heading out for holiday.

Strangely this seems to happen only when the zoom goes through the "pinch" code branch, rather than the "zoom" code branch. To see the difference, try zooming in and out by holding the control key and scrolling up and down on your trackpad—the performance should be as expected.

**Comment by mimecuvalo** [comment]
We've greatly improved this (thx @MitjaBezensek!). Thanks for reporting! Please do reopen though if it's still causing issues though.
