### ISSUE TITLE
[Feature]: Components - Repeatable instances of a "master component"

### ISSUE THREAD

**Issue by ijpatricio** [tldraw/tldraw#1813]
### What's the feature?

Resembling a Figma feature, I would like to make a "component" - imagine a naive button, with a rectangle, a text and an icon.

I want to use this "component" multiple times, and if I edit the "master", every other instance will update accordingly.
Ideally, the instances that had customizations would not change.

For example: if I change the text value on a button "instance", the text would remain. Changes to the icon or to the rectangle would be applied.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by steveruizok** [comment]
Components intuitively feel like a weird feature for a "lightweight" diagramming app like tldraw, though I've certainly wished I had them before while using the app. In general though, components feel likea slippery slope into a full on design / Figma feature set (with constraints, pinning, autolayout, etc.) whereas I think there's value in the default tldraw experience being something more quick and dirty and less precise. 

I'd still like to implement components as a sort of plugin though, but mostly because I know developers would appreciate it as something to use in other apps built on top of tldraw. And I'm also curious about what a good implementation would look like.

In any case, I expect we'll first have something like the Draw.io / Excalidraw "libraries" feature (see #1345) this year. While not having main-instance relationships, this could help with some of the intent you're describing.

**Comment by mimecuvalo** [comment]
rolling up into https://github.com/tldraw/tldraw/issues/1345
