### ISSUE TITLE
[Bug]: If you use hideUI prop, you cannot use the keyboard. 

### ISSUE THREAD

**Issue by xabierlameiro** [tldraw/tldraw#1854]
### What happened?

Hello, when you use tldraw "^2.0.0-alpha.14" with this config :
` <Tldraw hideUi />`
It is not possible to use copy and paste with the keyboard.
The temporary solution that I have found is, not to use that prop and :
`.tlui-layout {
    display: none;
}`
Maybe I'm screwing up, and this is on purpose. But I need to use the keys without displaying the user interface.

Regards,
Xabier

### How can we reproduce the bug?

Given : "@tldraw/tldraw": "^2.0.0-alpha.14" in my project
When : i'm use the hideUI prop in tldraw component and try to paste anything
Then : don't work

### What browsers are you seeing the problem on?

Chrome

### Contact Details

xabier.lameiro@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by judicaelandria** [comment]
That's intended and they mentioned it here
https://github.com/tldraw/tldraw/blob/20704ea41768f0746480bd840b008ecda9778627/packages/tldraw/src/lib/ui/TldrawUi.tsx#L102-L104

When you pass the hideUi props, the `TldrawUiContent` is not mounted but thats the component who is responsible for calling `useKeyboardShortcuts` hooks
>.tlui-layout { display: none; }
>Maybe I'm screwing up, and this is on purpose. But I need to use the keys without displaying the user interface.

so, no you're not screwing up that's how you do it :)

**Comment by nickdandakis** [comment]
Ran into this as well and can work on a PR for moving keyboard shortcut handling out of the UI layer. Would like to additionally move `defaultExternalContentHandlers` out of the UI layer as well. This would enable shortcuts, copy/pasting, and drag and drop functionality even when `hideUi` is on which was the expectation (for me anyway).

Can a core contributor confirm my assumptions for the change here?

For moving keyboard shortcut handling out of the UI layer:

1. Move `useNativeClipboardEvents()` hook out of `<TldrawUiContent />` (aka the UI layer React component)
2. Create new `<InsideOfEditorContext />` component in main `<Tldraw />` component, above and decoupled from the `<TldrawUi />` component
3. Move `useNativeClipboardEvents()` hook into new `<InsideOfEditorContext />` component
4. Refactor `useNativeClipboardEvents()` hook to drop the dependency on `useToolbarItems()`. I'm a little unsure why that's there but will do some digging

Then for moving default external content handlers out of the UI layer:

1. Move `registerDefaultExternalContentHandlers()` out of `<InsideOfEditorAndUiContext />` and into `<InsideOfEditorContext />` 
2. Refactor `registerDefaultExternalContentHandlers()` to emit editor events for errors instead of firing `toasts` (is this the preferred approach here? will do some more digging to see how this is usually handled here)

**Comment by TheNerdKid** [comment]
I'd love to see this implemented!

**Comment by steveruizok** [comment]
So sorry for missing this! Fix inbound https://github.com/tldraw/tldraw/pull/7367
