### ISSUE TITLE
local development, i yarn install in root dir, and in /apps/examples/, run yarn && yarn dev, get the error 

### ISSUE THREAD

**Issue by labike** [tldraw/tldraw#1882]
```
10:26:47 [vite] Internal server error: Failed to resolve import "@tldraw/tldraw/tldraw.css" from "src\examples\UserPresenceExample.tsx". Does the file exist?
  Plugin: vite:import-analysis
  File: D:/tldraw/apps/examples/src/examples/UserPresenceExample.tsx:3:7
  1  |  import { jsxDEV } from "react/jsx-dev-runtime";
  2  |  import { InstancePresenceRecordType, Tldraw } from "@tldraw/tldraw";
  3  |  import "@tldraw/tldraw/tldraw.css";
     |          ^
  4  |  import { useRef } from "react";
  5  |  const USER_NAME = "huppy da arrow";
      at formatError (file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42597:46)
      at TransformContext.error (file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42593:19)
      at normalizeUrl (file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40509:33)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40652:47
      at async Promise.all (index 2)
      at async TransformContext.transform (file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:40578:13)
      at async Object.transform (file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:42871:30)
      at async loadAndTransform (file:///D:/tldraw/node_modules/vite/dist/node/chunks/dep-f7d05e3f.js:53335:29)
```

**Comment by Norlandz** [comment]
### in short 
its a css file `tldraw.css` missing, 
you can get it from by npm install the project 
and paste it in your local dev project
- (Idk why such error, I just tried and it worked)

### *procedure 
1. git clone the code from github, -- say this is your `DevProj`
1. create another new project -- say this is your `TempGetCssProj` \
   (-- **the whole point is to just get the css file**, you dont need this project)
1. in `TempGetCssProj`, run `yarn add @tldraw/tldraw@alpha`
1. now you can **search for `tldraw.css`** in that `TempGetCssProj`
![image](https://github.com/tldraw/tldraw/assets/43581880/3317e384-dfdf-4129-ac7c-4996256657ee)
1. now **copy** the css file from `TempGetCssProj`, & **paste** it into your `DevProj` -- `H:\Using\tldraw-contribute\tldraw-2.0.0-alpha.14\packages\tldraw`
![image](https://github.com/tldraw/tldraw/assets/43581880/d1095dc2-6516-4ef1-b61b-1baeeb5bc84a)

---
---

## For anyone who is starting the project, there are other steps you may need to take

#### simple steps (as shown in ReadMe)
1. clone the project 
1. run `yarn install` 
1. run `yarn dev`

#### use `yarn install`, Not `npm install` 
otherwise some error about the "workspace & dependency" can show up 

#### you may need to install some packages **Globally**
-- follow the instruction on the Error in your Cmd, it tells you what you are missing
```
npm install -g vite
npm install -g chokidar
npm install -g chokidar-cli
...
npm install -g concurrently
npm install -g tsx
...
```

#### (you dont need to `yarn add` to add any more local packages (except the global ones mentioned))

#### env var setting in Windows

in `H:\Using\tldraw-contribute\tldraw-2.0.0-alpha.14\apps\examples\package.json`

change the following, so you can run the env var in Windows 

```
	"scripts": {
		"// dev": "concurrently \"vite\" \"HOST=localhost PORT=1234 npx y-websocket\" --kill-others",
		"dev": "concurrently \"vite\" \"set HOST=localhost&& set PORT=1234&& npx y-websocket\" --kill-others",
```

#### there is no need to use wsl, powershell just works fine
(this wasted me a lot of time on)
(wsl even introduce errors about @esbuild/linux-x64)

#### you need to add the `tldraw.css` (as talked above)

### image for a working example & some procedure
![image](https://github.com/tldraw/tldraw/assets/43581880/6fd5d5fc-d0db-43ac-a7bb-75beb40c863e)


### Prior statement
- Im not using the current version, Im using the `tldraw-2.0.0-alpha.14` released version
- I just **tried** those, I make no guarantee those works / correct
- (the devs may update these to the ReadMe)

**Comment by Norlandz** [comment]
Its ignored intentionally in `.ignore` `packages/tldraw/tldraw.css`, idk why

**Comment by labike** [comment]
@Norlandz thanks, i'm try

**Comment by MURTOMAASORTAJA** [comment]
Stumbled upon this very same thing. I've seen notions here and there in release notes and in documentation that the CSS stuff is included but it is not.

Why wasn't it there? Did I do something wrong?
