### ISSUE TITLE
Arrows not displayed correctly

### ISSUE THREAD

**Issue by sylsa** [tldraw/tldraw#2104]
### What happened?

 tldraw version 2.0.0-alpha.16
1. create two tldraw in one page  and draw an arrow, then copy the status to another tldraw using TLstore and snapshot.
2. when dragging the arrow in the  front tldraw to make arrow length shorter, the arrow in the last tldraw will also change( but its start and finish points are still shown correctly ).

### How can we reproduce the bug?

1. `const [store1] = useState(() => createTLStore({ shapeUtils: defaultShapeUtils }));
 const [store2] = useState(() => createTLStore({ shapeUtils: defaultShapeUtils }));
const [snapshot, setSnapshot] = useState();`
 `<Tldraw store={store1}>
 <Tldraw store={store1}>`

2.then draw an arrow
3. `const snapshotTemp = store1.getSnapshot();setSnapshot(snapshotTemp);store2.loadSnapshot(snapshot);`
4. dragging the arrow in the  front tldraw 

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mimecuvalo** [comment]
It's hard to say your exact bug but it sounds like you have two editors with maybe the same `persistenceKey` and they are maybe sharing the same store. Try changing the `persistenceKey` so that they point to two separate places and that way they won't be sharing changes.

Please reopen this issue if you maybe have a screenshot or more details and we can try to figure it out more together!
