### ISSUE TITLE
Add paint bucket for color fill

### ISSUE THREAD

**Issue by hypertexthero** [tldraw/tldraw#2301]
### What's the feature?

I’d like a **paint bucket** tool to fill shapes with colors.

Two examples: 

1. [MacPaint](https://en.wikipedia.org/wiki/MacPaint#/media/File:MacpaintWP.png) [interface](https://lowendmac.com/2016/macpaint-the-genesis-of-mac-artwork/)
2. [Photoshop paint bucket tool](https://www.adobe.com/products/photoshop/paint-bucket-tool.html)

Thank you for making tldraw. I love it!

Simon

### Contact Details

simon@hypertexthero.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by anugoyal998** [comment]
I would like to work on it.
Please it to me.

**Comment by steveruizok** [comment]
Thanks for the issue @hypertexthero. We won’t be implementing a paint bucket in tldraw. This canvas is an “object based” canvas like Figma or Keynote rather than a “pixel based” canvas like Photoshop or Paint. The fill algorithms that are used in pixel canvases won’t work here, and would combine poorly with other systems and features that we have. 

This may be related to requests for a “solid fill” style for shapes, which we’re considering!

**Comment by breck7** [comment]
You can implement this as an object based system. Instead of filling pixels, you find the boundaries of the fill and replace the line with a solid polygon implementing that shape.

**Comment by corysimmons** [comment]
@steveruizok wait what? You can make a closed vector shape and add fill to it pretty easy. I find myself reaching for this all the time and wondering why TLDraw doesn't have it. If you're saying you can't do this because the draw tool is raster, then why not just add a dead simple pen tool?

**Comment by steveruizok** [comment]
Yeah you can make closed shapes, including draw shapes. If the issue is saying a tool to apply those styles, that would be easy (though not sure it's needed). I could also imagine a tool that would create new geometric fill shapes in contiguous spaces, which would sort of be different but also very fun

**Comment by corysimmons** [comment]
My use case is frequently I just want to use the brush tool to draw a weird, closed shape then click a bucket icon to fill it. If that's not doable because rasters or something, then a dead simple pen tool and some UI to fill a closed shape.

I find myself reaching for this _all_ the time and I'm sure I'm not alone.
