### ISSUE TITLE
[Bug]: Bookmarks not showing image and description preview in VS Code extension

### ISSUE THREAD

**Issue by pranjaldugar** [tldraw/tldraw#2363]
### What happened?

:) Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by pranjaldugar** [comment]
Adding to this it would also be great if we can use favicon when background image (social image) not found.

**Comment by steveruizok** [comment]
Hey @pranjaldugar, we did try that early on! But it looked pretty broken in most cases. 

This does look like it could be a bug though, @MitjaBezensek can you take a look? 

For additional context: on tldraw.com, we get social data from an endpoint that is designed to fetch it safely, and use a less reliable “backup” strategy when that fails. In the VS code extension, we have to rely only on this “backup” strategy because the VS code extension needs to work independently.

**Comment by MitjaBezensek** [comment]
Nice catch! Just created a PR that should solve it. If all goes well this will be fixed next week when we do a new release of the extension.
