### ISSUE TITLE
[bug] Menu modifier keys are ugly on Windows

### ISSUE THREAD

**Issue by Tyriar** [tldraw/tldraw#243]
Guessing on mac you use the nice cmd icon but on Windows it's quite ugly, 

![image](https://user-images.githubusercontent.com/2193314/141170956-4881eed7-9e0f-4e40-ba30-8f5503e73fa0.png)

Looks a little better without the padding:

![image](https://user-images.githubusercontent.com/2193314/141171176-93b831ef-93b6-4282-8f20-4ecc1a2c4700.png)

**Comment by benoitgrelard** [comment]
Hey @steveruizok, this is a common issue people tend to have when implementing dark mode too for example.
I'm guessing what you're talking about is similar.

If that's the case, by far the simplest way would be to set your theme `className` on the body rather than having to re-apply it strategically like you describe. You can do this easily in an effect instead of declaratively in your container.

**Comment by steveruizok** [comment]
Unfortunately that won't work in my case because the component I'm working on is distributed as a library. If there are two components on the same page, then they should theoretically be able to have different theme. IIRC I couldn't do that if I were setting the theme on the body.

(This is a weird and extra edgy case, I'm sure.)
