### ISSUE TITLE
Failed to migrate store: target-version-too-old

### ISSUE THREAD

**Issue by keiyamamoto340** [tldraw/tldraw#2531]
Hey, I ran into an error while using tldraw:

```js
Error: Failed to migrate store: target-version-too-old
    at TLLocalSyncClient.connect (webpack-internal:///(app-pages-browser)/./node_modules/@tldraw/editor/dist-esm/lib/utils/sync/TLLocalSyncClient.mjs:131:23)
```

My browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36 Edg/120.0.0.0

**Comment by MitjaBezensek** [comment]
This happens when there's a data model change and you try to open a new document (one that has some new changes to the data model) in an older version of the code that doesn't know about those changes. Usually only happens in dev mode. Best thing to do it probably to do a hard reset of the data and continue from there.

Closing for now but let us know if you still face this issue.
