### ISSUE TITLE
Cannot delete a URL I shared by mistake.

### ISSUE THREAD

**Issue by dnmids** [tldraw/tldraw#2812]
Hi, I urgently need to delete an URL I shared by mistake, or the content I created under this URL. How to achieve that? 
Thank you!

**Comment by h2thien** [comment]
Hey @dnmids sorry to hear. I suppose you shared a snapshot, and not a project, is that right? If so, I think it's not possible **for a user** to delete a snapshot. I guess this is mainly because you can create a snapshot as a guest users, so there's nothing guarantee your ownership of the snapshot to delete it.

Anyway, I do think it's possible **for (an admin at?) tldraw** to delete a snapshot for you. I assume you don't want to spread the snapshot further, so my suggestion is to contact them via private email. There's an email in the [license page](https://tldraw.dev/community/license) that could work?

**Comment by dnmids** [comment]
thank you for the fast response @h2thien  - I'm not sure i shared the snapshot or the read-only link. I've already contacted tldraw via hello@.... and will wait for their response. I appreciate your assistance. let me know if you can think of any other way to delete the content I shared. Thanks!

**Comment by Taha-Hassan-Git** [comment]
Hi, I seem to remember this issue was resolved. Is that right?

**Comment by dnmids** [comment]
Yea thank you so much
