### ISSUE TITLE
Ability to resize Notes

### ISSUE THREAD

**Issue by AccessViolation95** [tldraw/tldraw#2875]
### What's the feature?

Notes can be rotated, but not resized. They automatically expand downwards to fit the text content, and I think being able to manually resize them, at least in the horizontal direction, would be great for these reasons:
- Making a Note larger can create empty space which can be used by placing drawings on it for additional visual context;
- Notes with long lines such as bullet point lists or source code would look better with less or no wrapping, which could be achieved by making the Note wider than the lines are long.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
Hey! Thanks for the suggestion. Sticky notes just got a big facelift and we talked about resizing a lot during the development process. Ultimately we decided against it as we felt that arriving at a document and finding sticky notes in a wide variety of shapes and sizes kind of ruins their effect. 

That isn't to say it'll never happen, though!

**Comment by MrLixm** [comment]
Hello, coming back on this because I really feel that it is a missed opportunity.
For the argument about _"finding sticky notes in a wide variety of shapes"_ I think it should just be up to the author to maintain similar scaling across its notes, but leave the freedom for anyone to scale them as pleased.

I do not know the original design intentions of notes but for me it is to provide a visual difference with the rest of the diagram, a bit like an admonition in a rich text document. But currently, because I cannot resize them:
-  or the content endedup being not formatted as expected:
   ![tldraw screenshot](https://github.com/tldraw/tldraw/assets/64362465/ee207977-a3fb-4d1c-8cbe-af26569bd017)
   > ^ this is supposed to be a primitive representation of a filesystem hierarchy

- or the auto resizing just doesn't fit with the layout on the diagram. 

Which in both cases result in I just using a basic text or a regular shape but which will always looks to be part of the diagram when it should not.

So I really hope that idea is revisited in the future 🤞 
Cheers.
Liam.

**Comment by dimateos** [comment]
> finding sticky notes in a wide variety of shapes and sizes kind of ruins their effect.

Well the actual note size depends on the zoom you were at creation type + the note font size, so the effect is very easily ruined already 😭 

* When I am working on a big canvas the zoom level changes all the time... so whenever I create a sticky note it basically has a random size!
* I usually create it where where I am on the canvas but then bring them together
  * I always end up having to copy/paste or extend a previously created one if I want to keep the size consistent (and then copy/paste the text)...
* IMO it does not make much sense to allow rotation but not scale?
  * I sometimes use rotation on some notes to give then emphasis so why not size too?
  * Let the user decide if they want an organized or chaotic stickies. In my case it would help me to preserve the mentioned "effect" by making any note match the size of already existing ones!
* Same with text font size without manual resizing
  * You can increase the font but the note only scales vertically! This breaks any line with more than 2 words into too many lines...

![image](https://github.com/user-attachments/assets/2b736fd2-ff7a-4155-a288-108f3e6a28b2)

BTW when you have stickies in a group weird stuff happens (as expected due to the resize constraint).
This makes them useless inside groups when you need to adjust size for a given composition of elements to work, etc...

![2024-10-16_(201120)_chrome](https://github.com/user-attachments/assets/e5302050-961f-4c91-a008-0a2860a26891)
