### ISSUE TITLE
Page rename menu button doesn't work on firefox

### ISSUE THREAD

**Issue by SomeHats** [tldraw/tldraw#2903]
Also it disappears after its been clicked?

![Image](https://uploads.linear.app/8ba8cf67-bb46-4faa-8a97-5eb61e0814c1/689d1db7-1429-4e19-84c9-35b075b6bdd4/acd1b051-af64-4076-a17c-7aad3e55eeef?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhiYThjZjY3LWJiNDYtNGZhYS04YTk3LTVlYjYxZTA4MTRjMS82ODlkMWRiNy0xNDI5LTRlMTktODRjOS0zNWIwNzViNmJkZDQvYWNkMWIwNTEtYWY2NC00MDc2LWExN2MtN2FhZDNlNTVlZWVmIiwiaWF0IjoxNzA5NDA4NDkyLCJleHAiOjMzMjc5OTY4NDkyfQ.G0_84fI0x7BTj2nWmAwAYzKJAwfswR2FL0dtAaT99zw)

**Comment by olaleykhan** [comment]
Hi Hi. I'm looking to contribute to this project. I am still quite new to open source
I looked into this issue and found out some things.

1. the disappearance of the Rename is the expected behavior. when the page title is in edit state, there is no point being able to click rename again.
2. Clicking on the edit button (Edit.svg icon) exhibits similar behavior as clicking on the rename button. (I.E, Rename button disappears | User is able to rearrange page order | User is able to rename all/any page without clicking rename again | the name of the current page to be renamed is highlighted with blue background ).

3. On rename,  the name of the page being renamed is highlighted blue. however, the shades of blue on Firefox differs from that on chrome. while on @SomeHats screen record, it does not even show at all.

4. as explained in 3 above, the Screen record posted by @SomeHats  does not highlight the names to be edited as in blue, hence the probable reason why it appears as though the feature is not working. 
(Notice how in the screen record, the "drag-handle-dots.svg" appear and the edit icon changes to a check icon. However, it is not highlightred blue. My guess is the edit still works if you actually try to edit the name. 

5. I am unable to replicate the bug as it works just fine on my PC. (both windows and linux)

6. I found this workaround in the codebase. it might be the cause of the issue but I cannot test since I am unable to replicate the problem. 

https://github.com/tldraw/tldraw/blob/15c760f7ea9523c7f52aef48c8ca0f1563f774a6/packages/tldraw/src/lib/ui/components/primitives/TldrawUiDropdownMenu.tsx#L50

**Comment by olaleykhan** [comment]
![TL-rnm](https://github.com/tldraw/tldraw/assets/53246916/18b649f2-740f-44b9-aaf1-e3476b7a1440)

**Comment by olaleykhan** [comment]
@steveruizok @SomeHats

**Comment by MitjaBezensek** [comment]
Looks like this was fixed

https://github.com/user-attachments/assets/19415384-cbcb-4509-8a55-3075afe044b6
