### ISSUE TITLE
[Feature]: Notify of failed asset upload to .xyz server

### ISSUE THREAD

**Issue by bmitchinson** [tldraw/tldraw#2944]
### What's the feature?

When assets.tldraw.xyz is blocked by the network, there's no indication to users that assets failed to upload.

Ex: I upload an image, spend an hour annotating it with text. I click "share" and it looks like everything worked correctly. Behind the scenes, the image failed to upload, but I'm unaware because the cached image on my client looks fine. Others view the link and are then confused.

I work somewhere where the .com isn't blocked, but the .xyz is. Wondering if the domains could be consolidated, or if in the short term, an "asset failed to upload" warning could pop up.

When the upload fails, this log appears. (It complains about CORS but I think it's really just our firewall blocking the .xyz)
It'd be nice if I didn't have to explain to people that they need to check their logs.

![console log](https://github.com/tldraw/tldraw/assets/33632286/6f37a876-e2a3-4a4a-bf0f-2043f5c98363)

### Contact Details

mitchinson.dev@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ds300** [comment]
This is great feedback, thank you.

The domain consolidation should be possible but last time we looked into it we got a bit stuck, I forget exactly why. I will take another look briefly.

Regardless it totally makes sense to let people know if their uploads didn't work 👍🏼 A little toast will be better than nothing. I'll do that now and put a PR up.

**Comment by bmitchinson** [comment]
Sweet, thanks!

The toast notification will lesson the burn, but until domain consolidation happens we'll be unable to use the app due to corporate firewall stuff.

**Comment by ds300** [comment]
Update on the domain issue, I explored a couple of ways to resolve it this morning:

1. We _could_ use a reverse proxy routing setting in the vercel app config. POC here https://github.com/tldraw/tldraw/pull/2967
  - This would make it so that rather than POST-ing to `assets.tldraw.xyz/uploads/*` it would be `tldraw.com/uploads/*`
  - This would be slightly worse for perf but probably not noticeably so, certainly not for uploads. We could test download perf easily enough.
2. The ideal solution would be to use a CNAME record to reroute traffic from `assets.tldraw.com` to `assets.tldraw.xyz` but doing this right involves some tricky certificate wrangling and arcane clicking in the cloudflare dashboard and none of us are super experienced with that kind of thing so it's a little scary.

I will take another look at 2 tomorrow and if it still seems scary I'll work on making 1 happen.

**Comment by ds300** [comment]
Using vercel as a reverse proxy made downloads like 3x-4x slower (!!!!) so it's a no-go. Will investigate the DNS option.

**Comment by bmitchinson** [comment]
Thank you looking + following up here! I'd imagine it's tempting to punt on the dns issue but, sounds like resolving it once and for all would be a great item to cross off.

If there's any information gathering I can do to help just lmk 👍

**Comment by ds300** [comment]
Still planning to do this but it's been bumped by some higher-priority work I'm afraid, and it looks like it will cost us some money so that might might create extra delay.

Is it tricky for you to get the .xyz domain added to your company firewall allowlist?

**Comment by bmitchinson** [comment]
Unfortunately yes, federal work. But I'll do my best 👍 
Thanks for the info

**Comment by mimecuvalo** [comment]
We have a toast now when a file fails to upload 👍
