### ISSUE TITLE
[Bug]: Wrong initial page name in browser with another language

### ISSUE THREAD

**Issue by manuklapf** [tldraw/tldraw#3237]
### What happened?

When creating an editor in a different browser language than English, the initial page name is wrong.

<img width="275" alt="image" src="https://github.com/tldraw/tldraw/assets/39298467/76babd91-6eb9-4318-b2ae-fa970fa65882">

### How can we reproduce the bug?

Go to www.tldraw.com and create new pages in a different language than English.

### What browsers are you seeing the problem on?

Chrome, Safari

### Contact Details

manuel.klapfenberger@ghostthinker.de

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by olaleykhan** [comment]
@steveruizok . if this is considered a bug, I figured it's caused by the hardcoded "page 1" value in the TLStore.

https://github.com/tldraw/tldraw/blob/a8477d00faf530c963fd0acba9f5ada9281e32dc/packages/tlschema/src/TLStore.ts#L86

It needs to be translated while passing the string.

I don't think it's a good first issue because the useTranslation hook can't be used outside a react component and also cannot be exported from TLDraw to the TLStore.
