### ISSUE TITLE
[bug] Not able to see delete icon in Android phone 

### ISSUE THREAD

**Issue by Proful** [tldraw/tldraw#328]
![Screenshot_20211121_124248](https://user-images.githubusercontent.com/354596/142746099-8828a156-c7d4-4f1e-b219-ea22c6f31677.jpg)

**Comment by beatrizoliveiira** [comment]
What are the specifications of your android phone?
I am using a Samsung Galaxy A50 with the Chrome browser and the delete button appears for me: 

![image](https://user-images.githubusercontent.com/65451957/142772139-e1f78e94-c55c-4e39-95ab-fb7d1e4f1171.png)

**Comment by zakariaelas** [comment]
I tried playing around with this in the chrome dev tools by toggling the device toolbar and it seems to happen whenever screen_size <= ~380px 

![image](https://user-images.githubusercontent.com/33696020/142774569-e44e2354-c463-4f35-8a21-69adbe3b7998.png)

One quick fix would be to set `flex-wrap: wrap` on the `Panel` component right [here](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/components/ToolsPanel/PrimaryTools.tsx#L51), but i'm not entirely sure if this is the best approach (ping @steveruizok). 

Setting `flex-wrap: wrap` on the `Panel` and `flex-shrink: 0` on `ActionButton` (so that the circle does not turn into an oval) would yield the following 

![image](https://user-images.githubusercontent.com/33696020/142774758-735d6ac7-95c7-4af3-bf32-1a3aaeaad3c7.png)

What do you think? If this is up for grabs, I can attempt a PR. Really cool project btw!

**Comment by steveruizok** [comment]
I actually worked out the grid logic for the toolbar on the guide branch (the action / delete buttons wrap up "above" the primary tools). That branch still has lots of work to do on it, so I'll see if I can extract those styles into a separate PR to fix this.

**Comment by proful** [comment]
Resolution of my Android phone (where issue appear) = 2340 x 1080
