### ISSUE TITLE
[Feature]: Support other custom shapes to have clip path imposed on their children?

### ISSUE THREAD

**Issue by xmliszt** [tldraw/tldraw#3455]
### What's the feature?

I am creating my custom shape, which I would like it to behave similarly to the `TLFrameShape`, so that its children shapes will be clipped by its bound when the children are partially out of the bound like what is shown below.

![CleanShot 2024-04-12 at 14 37 51@2x](https://github.com/tldraw/tldraw/assets/44829092/e51e515d-e100-4b87-9d85-1f64f477b8bf)

By looking at the source code, I realize this is not possible because https://github.com/tldraw/tldraw/blob/main/packages/editor/src/lib/editor/Editor.ts#L3999-L4001 suggests that we are only getting the masks from ancestors which are strictly `TLFrameShape`. 

![carbon](https://github.com/tldraw/tldraw/assets/44829092/8b4b3956-0d86-453c-907a-b1ed5b52758e)

I am not sure if there is a workaround such that I can let the editor use my custom shape type to determine the masks area? Or if not, perhaps it could be a feature enhancement?

### Contact Details

xmliszt@gmail.com

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jezzzm** [comment]
hi @steveruizok, running into this issue as well. would be great to expose a `shouldClipChildren` method on `TLShape` instead of hardcoding this.

we're evaluating tldraw as the basis for an updated slide editor in our saas. we'd really like to be able to create a `slide` shape which is essentially a stricter version of `frame`, with some additional props. but we can't do this nicely with the same clipping until this isn't hardcoded as highlighted by @xmliszt.

i can't imagine this is particularly difficult - am happy to contribute changes but not sure if this is still in your backlog anyway.

thanks!

ps. sorry for direct ping
