### ISSUE TITLE
Unable to preventDefault error on every gesture

### ISSUE THREAD

**Issue by varunneal** [tldraw/tldraw#3686]
### What happened?

"Unable to preventDefault inside passive event listener invocation" is logged as an error in the console on every gesture.

I discovered this while testing locally but found that it even happens on the main site tldraw.com. 

### How can we reproduce the bug?

Using a macbook (pro, m1) on chrome, open the console on tldraw.com. Draw anything. 
<img width="442" alt="Screenshot 2024-05-02 at 5 20 34 PM" src="https://github.com/tldraw/tldraw/assets/32204417/3315eaa4-5593-48e6-adc2-826dfce0345b">

### What browsers are you seeing the problem on?

Chrome

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
I'm not seeing this on my side. What version of Chrome are you using? Is this a local room or a multiplayer room? Can you try without browser extensions?

**Comment by cketcham** [comment]
I can reliably reproduce if I choose a device in chrome. The issue seems to be related to `onTouchStart` listeners that are set to passive by default so you can't prevent default behavior.

I'm not sure why those need default behavior prevented, do you know? I tried it and didn't notice any weird behavior.. but definitely could have just been because I didn't test extensively.

Looks like it's possible to manually add and remove event handlers ourselves though.

Do you prefer one or the other of those solutions?

**Comment by mimecuvalo** [comment]
I am able to repro but only currently on mobile. Happens via `useCanvasEvents`
