### ISSUE TITLE
Local images

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#3728]
In local projects, could we put images separately into indexeddb, and then use the image src to point to it? Is there a more efficient way of doing local images?

**Comment by danolekh** [comment]
This issue seems resolved, yet I cannot find anything related how to store blob separately in indexed db - as it was implemented in PR  #3836
I also didn't find any examples on how to do this. Was api removed in favor of something else? If so, how would implementing something that Steve asked would look like?

**Comment by danolekh** [comment]
> This issue seems resolved, yet I cannot find anything related how to store blob separately in indexed db - as it was implemented in PR [#3836](https://github.com/tldraw/tldraw/pull/3836) I also didn't find any examples on how to do this. Was api removed in favor of something else? If so, how would implementing something that Steve asked would look like?

Okay, I see PR #4068. Exactly what I looked for
