### ISSUE TITLE
[bug] Group shape behavior

### ISSUE THREAD

**Issue by steveruizok** [tldraw/tldraw#388]
Something's up with group behavior.

![Kapture 2021-11-26 at 15 09 59](https://user-images.githubusercontent.com/23072548/143610907-b10e08d3-72d6-4af6-9f56-e20f7c2c9dca.gif)

- create a rectangle
- create text
- group shapes
- double click text to select it
- double click text to edit it
- click outside to blur text
- move text or rectangle around

**Comment by lichin-lin** [comment]
Hi @steveruizok I have some idea about this issue:

When the user clicks on some children in a group, [the logic](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/state/tools/SelectTool/SelectTool.ts#L507) in **SelectTool.ts** will set the `selectedGroupId` into some value, but when the user clicks outside of the group, or, on the canvas, there's no logic to clean up the `selectedGroupId`. That's why the second time user click on the group, it will directly drill in and select the children.

you might want to try to handle the clean up in `onPointDown()`, and also when user press the `Esc` key to remove focus from the selection:

```js
onPointerDown: TLPointerEventHandler = (info, e) => {
  ...
  if (info.target === 'canvas' && this.status === Status.Idle) {
    this.selectedGroupId = undefined
    ...
  }
  ...
}
```

**Comment by steveruizok** [comment]
Thanks for the analysis! Want to make a PR? If not, I can come back to this in a few days and try to apply your fix.

**Comment by lichin-lin** [comment]
yes! i am working on it! but some how one of the test case in `SelectTool.spec.ts` can't pass (**Edits grouped text on double click after selecting**) 😢, the behavior is different when the double click happens in the test env versus actual user trigger it.

**Comment by steveruizok** [comment]
Right on! Don't worry about that, feel free to skip the test or write it as a todo. (It may be an issue with the tests themselves).

**Comment by judicaelandria** [comment]
it has been fixed!
