### ISSUE TITLE
[feature] Custom data attributes on shapes

### ISSUE THREAD

**Issue by nileshtrivedi** [tldraw/tldraw#408]
It would be really useful if the editor allows users to add and edit custom data attributes per shape. The use-case I personally have is using TLDraw as a visual graph (with labeled nodes and labeled edges) dataset editor with collaboration with team members - in order to build a skill-tree for a game. Once it's exported to JSON, it can be parsed and processed in various ways. But I couldn't find any visual graph dataset editor apps.

This could be exposed in the context menu for each shape.

**Comment by steveruizok** [comment]
You'd probably want to build on tldraw/core for that kind of application, in which case you absolutely could add whatever extra data attributes you wanted to your shape definitions. (You would be extending that basic `TLShape` interface). Maybe start by hacking on the core-example-advanced project?

**Comment by steveruizok** [comment]
Interesting use case though. If I understand correctly you would want to use tldraw.com to do the editing for the skill tree, but then parse it out automatically based on the document? In that case, I could see the argument for using tldraw.com rather than building something new. 

The shapes do have "name" properties (though not exposed in the UI) that could be used for this kind of arbitrary data. Once we add an objects panel (with renaming), that could be an option?

**Comment by nileshtrivedi** [comment]
I am using a hack right now. I only use text nodes and arrows connecting them. And then I put text in this format: `name: param1: value1, param2: value2`. When I export the JSON of the page, I'm then able to recover these data points which fulfills my immediate need. I am unable to name the edges though, which means I can't store things like edge-weights or distances or costs. But my current use-case does not need it.

**Comment by steveruizok** [comment]
Interesting. I'm surprised there isn't a tool better suited to this! But I'd love to see one built with tldraw/core. :)

**Comment by steveruizok** [comment]
I'm going to close this issue because it's not actionable. I'll keep this kind of thing in mind, though; it could be a use for something like a plug-in that uses the public Window.app API.
