### ISSUE TITLE
image/tiff support 

### ISSUE THREAD

**Issue by kobe651jp** [tldraw/tldraw#4282]
### What's the feature?

Can I add additional image formats to support? For my use case I need image/tiff support.

### Where would you like this feature?

The developer package

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
We don't support tiff because we rely on the browser to render images, and browsers don't support tiff.

You could add support for tiff yourself using a [`TLAssetStore`](https://tldraw.dev/reference/tlschema/TLAssetStore) and passing it in with the `assets` prop on the tldraw component, or when you create your store if you do that separately.

You would need to upload your tiff file somewhere in the `upload` handler and return a URL to it. The server you upload it to would need to be capable of transforming the tiff file into a format supported by web browsers - see https://developer.mozilla.org/en-US/docs/Web/Media/Formats/Image_types. Then, in the `resolve` method, you could rewrite your `.tiff` URL into a URL for your converted file which would be used by tldraw when rendering the images.

You'd need to pass the [`acceptedImageMimeTypes` prop](https://tldraw.dev/reference/tldraw/TldrawBaseProps#acceptedImageMimeTypes) to the tldraw component too

**Comment by mimecuvalo** [comment]
(closing as @SomeHats provided a solution, it's not something we'll add directly but you can certainly implement yourself in a custom version of tldraw!)
