### ISSUE TITLE
How to Customize the Note Tool to Align Text to the Top-Left Corner and Tilt Slightly to the Left?

### ISSUE THREAD

**Issue by Leyofficial** [tldraw/tldraw#4303]
### What's the example?

Hi tldraw team,

I'm currently working on a project using tldraw and I would like to customize an existing tool. Specifically, I want to modify the Note Tool so that the text is always aligned to the top-left corner instead of the center. Additionally, I would like the note to be slightly tilted to the left, similar to a note pinned on a board.

Could you provide guidance or examples on how to achieve these customizations? I'm particularly interested in changing the styles, alignment settings, and applying a slight tilt for the Note Tool.

This is what I need.
![Снимок экрана 2024-07-27 в 13 28 47](https://github.com/user-attachments/assets/db112341-826e-4921-8e37-9ec56397c061)

Thank you for your help!

Best regards,
leyofficial

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Taha-Hassan-Git** [comment]
This is an interesting one, and I can see a couple options for you. It depends on whether or not you're using your own custom UI. 

1. **Using tldraw's ui:** Customising default shapes isn't well-supported yet. If you're using tldraw's ui, the user will always have the option to change the alignment of the text on the shape in the UI, because the styles that are exposed for it in the style panel will be defined in the [shape's util](https://github.com/tldraw/tldraw/blob/2458db7a4e0936a3d954e05171a63335652b4691/packages/tldraw/src/lib/shapes/note/NoteShapeUtil.tsx#L51). My recommendation in this scenario would be to remove tldraw's note shape, create your own custom shape util and copy over the note shape code, changing the props, default props, component method etc. Anything you need to get the behaviour you're looking for. 
2. **Using a custom ui:** You can control what styles are exposed for each tool in your own style panel logic, so all you need to do is make sure they're created with the styles you want. One way is to use [side effects](https://tldraw.dev/docs/editor#Side-effects) to make sure that the note shape always had a particular rotation and alignment when created. Another way would be to use [setStyleForNextShapes()](https://tldraw.dev/reference/editor/Editor#setStyleForNextShapes) whenever the note tool was selected.

I'm not sure this is a great candidate for an example, because it's so specific. But I think we could maybe have an example of recommended ways to override default shape behaviour, because it's a pretty. common request.

Some examples that demonstrate the above concepts:
1. [Exposing styles for custom shapes.](https://tldraw.dev/examples/shapes/tools/shape-with-tldraw-styles)
2. [Overriding default menus.](https://tldraw.dev/examples/ui/custom-menus)
3. [Side effects.](https://tldraw.dev/examples/editor-api/before-create-update-shape)
4. [Using a custom UI.](https://tldraw.dev/examples/ui/custom-ui)

**Comment by Leyofficial** [comment]
Thank you for your response. I will try the concepts that you mentioned above and let you know if I have any issues.
