### ISSUE TITLE
Add toolbar element with file selection menu

### ISSUE THREAD

**Issue by Leyofficial** [tldraw/tldraw#4364]
### What's the example?

Hello! I hope you are doing well!

Can you help me please with this [code](https://github.com/tldraw/tldraw/blob/main/apps/simple-server-example/src/client/App.tsx) to catch the selection of an asset? I don't understand how I should call the tool in the navbar to bring up a menu with files to select.

Here is my ui
![Снимок экрана 2024-08-06 в 19 10 00](https://github.com/user-attachments/assets/f2f0ace4-f94f-4465-be81-66663c34f7d3)

Here's what [I did](https://github.com/xi-effect/xi.app/blob/36761802/packages/pkg.module.whiteboard/components/Navbar.tsx), it opens a menu to select pictures, and it works, but it only sends the picture data to the server and does not add it to the board.

Here's a [root component](https://github.com/xi-effect/xi.app/blob/36761802/packages/pkg.module.whiteboard/WhiteBoard.tsx) of the Tldraw Component

Thanks!

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SomeHats** [comment]
Take a look at how we do this for our own image tool in [`useInsertMedia`](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/lib/ui/hooks/useInsertMedia.ts).

As well as creating assets, you need to create image shapes that reference those assets too. We have a whole system already in place for handling that though, so accessing that by calling [`editor.putExternalContent`](https://tldraw.dev/reference/editor/Editor#putExternalContent) is probably the way to go.

In that world, the way to handle the uploading part is to supply a `TLAssetStore` with an `upload` method when you set up tldraw. That method should upload the file, and return a URL where it can be accessed in the future: https://tldraw.dev/examples/data/assets/hosted-images

It's better that you use the TLAssetStore because that will cover all the different ways images can get onto the canvas, like copy-paste and drag-and-drop.

**Comment by Leyofficial** [comment]
Thank you!

**Comment by Leyofficial** [comment]
Hello I did everything what you said previously but a have a error and I dont understand how to fix it. Also , Tldraw component doesn't support assets prop.
<img width="536" alt="Снимок экрана 2024-08-08 в 19 11 16" src="https://github.com/user-attachments/assets/419bc32a-bbaf-451b-9cbc-1dcec54da086">

> ### Property 'assets' does not exist on type 'IntrinsicAttributes & TldrawProps'

I have this error 
![Снимок экрана 2024-08-08 в 19 11 55](https://github.com/user-attachments/assets/f32287fb-ea1b-4a99-b879-9604b1b5b91d)

As you can see I have files that useInsertMedia return. But it doent work!

Thank you!

**Comment by Leyofficial** [comment]
[Here](https://github.com/xi-effect/xi.app/blob/36761802/packages/pkg.module.whiteboard/utils/useInsertMedia.ts) is my useInsertMedia hook , just in case I did something wrong in this hook

**Comment by SomeHats** [comment]
It looks like you might be on an old version of tldraw. What version are you using? Could you try upgrading to 2.4.x?

**Comment by Leyofficial** [comment]
Thank you! I forgot about that. You really helped me; I really appreciate it!
