### ISSUE TITLE
[Example Request]: Opening and cloaing the tluimenubar

### ISSUE THREAD

**Issue by mtalhastar** [tldraw/tldraw#4787]
### What's the example?

i want to hide and show this menu programmatically. How can I?
![image](https://github.com/user-attachments/assets/59dc646e-5fb4-4ade-ad48-81fd524e66c1)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MitjaBezensek** [comment]
You can open it via the editor menus:
```ts
editor.menus.addOpenMenu('actions-menu')
// clear it later
editor.menus.clearOpenMenus()
```

**Comment by mtalhastar** [comment]
![image](https://github.com/user-attachments/assets/6f742148-a234-4e5e-a236-3601f34cd88d)
actually i want this who thing to appear and disappear
@MitjaBezensek

**Comment by mtalhastar** [comment]
Would appreciate if you can write an example to open and close this programmatically thanks.
@MitjaBezensek

**Comment by Taha-Hassan-Git** [comment]
Hi there, the component you want to override is the MenuPanel. I don't think this is worth making an example for, because the custom components and custom menus examples alreadu cover the concepts you would need to implement this behaviour. However I've put together a bit of code that you can use as a starting point for your own solution:


```typescript
function CustomMenuPanel() {
	const [isOpen, setIsOpen] = useState(false)
	return (
		<>
			<button style={{ pointerEvents: 'all' }} onClick={() => setIsOpen(!isOpen)}>
				Toggle Menu
			</button>
			{isOpen && <DefaultMenuPanel />}
		</>
	)
}
const components: TLComponents = {
	MenuPanel: CustomMenuPanel,
}

export default function CustomMenuPanelExample() {
	return (
		<div className="tldraw__editor">
			<Tldraw components={components} />
		</div>
	)
}
```

![2024-10-28 at 11 43 38 - Gold Swift](https://github.com/user-attachments/assets/263ca3e4-d628-4c94-9565-2677ce687120)
