### ISSUE TITLE
[feature] Support style presets

### ISSUE THREAD

**Issue by yyyanghj** [tldraw/tldraw#707]
Allow users import a style preset for customization and teams sharing. 

Preset files need to include:
- font famlily
- color palette
- size or stroke width
- ...

**Comment by yyyang1996** [comment]
> Would this be useful for places where is embedded, or do are you thinking of this as a feature in the app (tldraw.com)?

Thank you for reply. I hope I can descirbe this clearly.

The original idea is users may need a color swatch to add/change colors like #644. If we implement this feature, should user need to change color repeatly when create a new project?

In addition to colors, users may also want to customize fonts, stroke widths etc. For instance, the small size is too thick for me. 

I think things like presets, theme configuration or settings is a good solution to keep the style menu interaction simple and friendly. We can do:
- Add a settings menu for user to edit the presets/configuration 
- Support export as a json file so that users can import this when they create a new project. 

And I think this should be a core feature of the [@tldraw/tldraw](https://github.com/tldraw/tldraw/tree/main/packages/tldraw).

For delelopers who want to integrate `@tldraw/tldraw` to their apps/websites, they can change the default styles to adapt design system. For now they have to clone tldraw repo and change [shape-styles.ts](https://github.com/tldraw/tldraw/blob/main/packages/tldraw/src/state/shapes/shared/shape-styles.ts) file, I am not sure if this is the only way. Also, it should be easy and just a few code to provide serveral built-in style presets on top of that. FYI, view screenshot of [draw.io](https://app.diagrams.net/) below. 

![drawio_styles](https://user-images.githubusercontent.com/34713301/172937525-b9f33001-f64e-4261-83ef-67e76a2dcb9c.jpg)

**Comment by steveruizok** [comment]
Right on @yyyanghj, thanks for the explanation. I'd say that this is out of scope for tldraw, at least on this version. I'll roll it into a feature ticket for the next big release, where we have a few other ideas about custom styles.
