### ISSUE TITLE
[feature] Be Able to Draw and Connect Lines Across Locked Components

### ISSUE THREAD

**Issue by 58bits** [tldraw/tldraw#733]
Not sure if this is a feature request or a bug, but in the attached video - we've locked a border component, and would like to connect one component on the left (outside) with a line to a component on the right (inside the locked border component) - but can't seem to get this to work. 

https://user-images.githubusercontent.com/405612/175027452-6f23b2be-c900-46f9-9ff9-99c367f891af.mp4

Thoughts?

**Comment by creampnx-x** [comment]
i think it is feature....

**Comment by steveruizok** [comment]
No, that's a bug! The arrow should ignore that locked shape.

Locking issue aside, it looks like the box shape is "above" the other two shapes, however. You could move that box to back (right click > Move > To Back, or `Shift + [`) so that the other shapes are "in front" of it, and receive the arrow first.

**Comment by 58bits** [comment]
@steveruizok thanks Steve! I'll give it a try.

**Comment by steveruizok** [comment]
Will be fixed by https://github.com/tldraw/tldraw/pull/745. Thanks for the catch @58bits !
