### ISSUE TITLE
[bug] Save project as doesn't work on safari and firefox

### ISSUE THREAD

**Issue by judicaelandria** [tldraw/tldraw#921]
Save as should open the file system handler so we can be able to give a name to the file

**Comment by judicaelandria** [comment]
@tomayac I think this has something to do with the function fileSave from "browser-fs-access", any idea?
https://github.com/tldraw/tldraw/pull/894#issuecomment-1211663872

**Comment by tomayac** [comment]
I'll take a look.

**Comment by tomayac** [comment]
I just tested the feature on… 

- Firefox 105.0b4 (64-bit)
- Firefox 104.0 (64-bit)
- Safari Technology Preview 152
- Safari 16.1

…and saving and opening  _per se_ worked fine.

Since `browser-fs-access` on Safari and Firefox internally uses `<a download>`, there is no browser-level save dialog. What could be done would be to show a tldraw-level dialog and ask for a name, which could then be passed to `fileSave()`, which would internally be translated to `<a download="passed-name.tldr">`.

This could look like [in this demo](https://glitch.com/edit/#!/imaginary-shadow-road):

```js
import {
  fileSave,
  supported,
} from 'https://unpkg.com/browser-fs-access@0.31.0/dist/index.modern.js';

const textArea = document.querySelector('textarea');
const button = document.querySelector('button');

button.addEventListener('click', async () => {
  const blob = new Blob([textArea.value], { type: 'text/plain' });
  let fileName = '';
  if (!supported) {
    fileName = prompt('Enter the desired file name!');
  }

  await fileSave(blob, {
    fileName,
  });
});
```

The relevant code already sort of supports this, but in the case of "Save As", the existing name `"New Document"` would need to be "forgotten":

https://github.com/tldraw/tldraw/blob/a22124b3a70b158bfd17441732de1e187fc34591/packages/tldraw/src/state/data/filesystem.ts#L33

**Comment by tomayac** [comment]
(If it helps, Excalidraw has the same "Save" vs. "Save As" workflow. See this [section of an article](https://web.dev/browser-fs-access/#real-life-code-sample) where we discuss this.

**Comment by judicaelandria** [comment]
Got it, thanks @tomayac
